### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by faxm0dem** [malbanGit/pitrex-baremetal#2]
I tested the latest image on my pitrex with a rpi0 v1.3
The vectrex screen stays black. How can I troubleshoot this ?

**Comment by amaiorano** [comment]
I recommend one of two ways:
1. Join the [Vextreme Discord](https://discord.gg/ddvne6qx), and ask in the #pitrex channel
2. Join the [Vectrex Fans Unite](https://www.facebook.com/groups/vectrex/about/) Facebook group (>5K members, very active) and ask there.

**Comment by malbanGit** [comment]
One issue was found some days ago, when using a PiZero instead of a PiZeroW. Perhaps that is the issue?

Documented in the mailing list for PiTrex at: [https://groups.io/g/pitrex-dev]()


---
The problem is just the changes in config.txt made to accomodate the Pi
Zero 2:

[pi0w]
kernel=pitrex.img
[pi02]
kernel=pitrex7.img

Changing pi0w to pi0 fixes the problem:

[pi0]
kernel=pitrex.img
[pi02]
kernel=pitrex7.img
---

**Comment by faxm0dem** [comment]
I added a `[pi0]` section and it worked !
Thanks !
